const express = require('express');
const router = express.Router();
const controller = require('../controllers/admin.controller');

router.get('/students', controller.getStudents);
router.post('/students', controller.createStudents);
router.put('/students/:id', controller.updateStudents);
router.delete('/students/:id', controller.deleteStudents);
router.get('/companies', controller.getCompanies);
router.post('/companies', controller.createCompanies);
router.put('/companies/:id', controller.updateCompanies);
router.delete('/companies/:id', controller.deleteCompanies);
router.get('/universities', controller.getUniversities);
router.post('/universities', controller.createUniversities);
router.put('/universities/:id', controller.updateUniversities);
router.delete('/universities/:id', controller.deleteUniversities);
router.get('/semesters', controller.getSemesters);
router.post('/semesters', controller.createSemesters);
router.put('/semesters/:id', controller.updateSemesters);
router.delete('/semesters/:id', controller.deleteSemesters);
router.get('/modules', controller.getModules);
router.post('/modules', controller.createModules);
router.put('/modules/:id', controller.updateModules);
router.delete('/modules/:id', controller.deleteModules);
router.get('/topics', controller.getTopics);
router.post('/topics', controller.createTopics);
router.put('/topics/:id', controller.updateTopics);
router.delete('/topics/:id', controller.deleteTopics);
router.get('/assignments', controller.getAssignments);
router.post('/assignments', controller.createAssignments);
router.put('/assignments/:id', controller.updateAssignments);
router.delete('/assignments/:id', controller.deleteAssignments);
router.get('/projects', controller.getProjects);
router.post('/projects', controller.createProjects);
router.put('/projects/:id', controller.updateProjects);
router.delete('/projects/:id', controller.deleteProjects);
router.get('/certificates', controller.getCertificates);
router.post('/certificates', controller.createCertificates);
router.put('/certificates/:id', controller.updateCertificates);
router.delete('/certificates/:id', controller.deleteCertificates);
router.get('/leaderboard', controller.getLeaderboard);
router.post('/leaderboard', controller.createLeaderboard);
router.put('/leaderboard/:id', controller.updateLeaderboard);
router.delete('/leaderboard/:id', controller.deleteLeaderboard);
router.get('/ai-prompts', controller.getAiPrompts);
router.post('/ai-prompts', controller.createAiPrompts);
router.put('/ai-prompts/:id', controller.updateAiPrompts);
router.delete('/ai-prompts/:id', controller.deleteAiPrompts);
router.get('/dashboard-analytics', controller.getDashboardAnalytics);
router.get('/feedback-management', controller.getFeedbackManagement);
router.get('/platform-settings', controller.getPlatformSettings);
router.get('/user-management', controller.getUserManagement);

module.exports = router;
